language: bash

os: osx

env:
  - JAVA_VERSION=8 RELEASE_STREAM=
  - JAVA_VERSION=11 RELEASE_STREAM=
  - JAVA_VERSION=8 RELEASE_STREAM=-lts
  - JAVA_VERSION=11 RELEASE_STREAM=-lts

script:
  - CASK_NAME="graalvm-ce${RELEASE_STREAM}-java${JAVA_VERSION}"
  # Check style
  - brew cask style Casks/${CASK_NAME}.rb
  # Install tap
  - GRAALVM_TAP_DIR="$(dirname $(dirname $(brew --repo homebrew/core)))/graalvm/homebrew-tap"
  - mkdir -p $(dirname $GRAALVM_TAP_DIR)
  - ln -s $(pwd) $GRAALVM_TAP_DIR
  # Install cask, extract its version, and update `PATH`
  - HOMEBREW_NO_AUTO_UPDATE=1 brew cask install --require-sha graalvm/tap/${CASK_NAME}
  - VERSION=$(brew cask info $CASK_NAME | head -n 1 | awk '{print $2}')
  - TARGET_DIR="/Library/Java/JavaVirtualMachines/${CASK_NAME}-${VERSION}"
  - export PATH="${TARGET_DIR}/Contents/Home/bin:${PATH}"
  # Ensure the expected `java` version is installed
  - test ! -z "$(java -version 2>&1 | grep $VERSION)"
  # Ensure GraalVM is picked up by `java_home`
  - /usr/libexec/java_home -V 2>&1 | grep "GraalVM CE"
  # Print versions of official languages
  - java -version
  - js --version
  - lli --version
  # Install and print versions of experimental languages and tools
  - gu install --no-progress python native-image R ruby
  - graalpython --version
  - native-image --version
  - R --version
  - ruby --version
